# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  # - &admin_duck 07FB96789934E76A3A442D4236D7F9B5EDBF141B
  # - &admin_duck C2A83A6A267A4F71B2C8FA4D30A24C7B3159CAEE
  - &server_powerspecnix age1vks9s5g7p0uhpe4eeregfga6zfcrpuxdjx8x2hwsdwe5hf77l5msxfujpe
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      # - *admin_duck
      - *server_powerspecnix
      age:
      - *admin_duck2
