alias reload!='. ~/.zshrc'
alias ll='ls -al --color=auto'
alias sagi='sudo apt-get install'
alias sasearch='sudo apt-cache search'
alias psgrep='ps -ef | grep -v grep | grep '
alias e='emacsclient -t'
alias ec='emacsclient -c'
alias vim='emacsclient -t'
alias vi='emacsclient -t'
alias k='gitk --all &'
