#!/bin/sh
TOGGL='~/.dotfiles/bin/toggl'

STATUS=`~/.dotfiles/bin/toggl now`

echo "$STATUS"
echo "$STATUS"
# echo
# echo \#FFFFFF

# exit 0

case $BLOCK_BUTTON in
    1) ~/.dotfiles/bin/toggl stop ;;
esac
